# Generated by Django 2.2.3 on 2019-10-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_useraccount_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
