# Generated by Django 2.2.3 on 2019-10-24 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20191024_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemImage',
        ),
        migrations.AddField(
            model_name='item',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 24, 16, 37, 4, 941639)),
        ),
    ]
