# Generated by Django 2.2.3 on 2019-10-24 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20191024_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 24, 16, 39, 11, 693320)),
        ),
    ]
